### ISSUE TITLE
Where does this live?

### ISSUE THREAD

**Issue by cranmer** [kratsg/statisfactory#1]
At some point we should think about where this repo should live. 
IRIS-HEP, it's own organization, scikit-hep, ...

As a specification it seems more general than python so wouldn't fit in scikit-hep. Maybe a reference implementation in python could live in scikit-hep. The specification itself might be nicer for IRIS-HEP.

**Comment by lgray** [comment]
I would propose
- Here while we are incubating it into a functional prototype with at least one backend (probably RooFit with some simple PDFs)
- IRIS-HEP while we're fleshing it out, adding PDF types, combine/pyhf
- scikit-hep when it's a truly advertisable / stable product

?

**Comment by cranmer** [comment]
I'm fine with scikit-hep for stable product / reference implementation.

Seems like we would still like to document the specification separately, and that might stay in IRIS-HEP.

**Comment by kratsg** [comment]
I'm moving this over to scikit-hep because we don't need to advertise it while we develop it, and can always specify beta releases/alpha releases/release candidates for now.

**Comment by kratsg** [comment]
https://github.com/scikit-hep/statisfactory/
